language: generic 

sudo: required 

services:
  - docker 

before_install:
  - docker build -t rev01ver/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true rev01ver/docker-react npm run test
