language: generic 

sudo: required 

services:
  - docker 

before_install:
  - docker build -t rev01ver/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true rev01ver/docker-react npm run test

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-971085020101"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
